modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/CrazyWoddMan/Warium-Create-Bridge/issues/"
license="MIT"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/warium-create"
    logoFile = "icon.png"
    credits="${credits}"
	authors="${mod_authors}" 
	description='''${mod_description}'''
    mixins = "mixins.${mod_id}.json"

[[dependencies.warium_create]]
    modId="forge"
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.warium_create]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.warium_create]]
    modId="crusty_chunks"
    mandatory=true 
    versionRange="${warium_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.warium_create]]
    modId="create"
    mandatory=true 
    versionRange="${create_version_range}"
    ordering="NONE"
    side="BOTH"